blank_issues_enabled: false
contact_links:
  - name: Questions / обсуждение
    url: https://github.com/fedorovstas1991-ship-it/YA-Proj/discussions
    about: Для вопросов и обсуждений используйте Discussions.
